
/*
Função criada para retornar o valor do contrato de acordo com seu preço e sua referencia atual
*/

CREATE FUNCTION SANKHYA.GET_VLR_CONTRATO(@P_NUMCONTRATO INT)
RETURNS FLOAT
AS
BEGIN
    DECLARE
    @VLRCONTRATO FLOAT;

SELECT
@VLRCONTRATO = SUM(VALOR)

FROM
TCSCON CON INNER JOIN TCSPRE PRE ON CON.NUMCONTRATO = PRE.NUMCONTRATO
WHERE CON.NUMCONTRATO = @P_NUMCONTRATO
AND (CAST(MONTH(REFERENCIA) AS VARCHAR)+'/'+CAST(YEAR(REFERENCIA) AS VARCHAR) = CAST(MONTH(GETDATE()) AS VARCHAR)+'/'+CAST(YEAR(GETDATE()) AS VARCHAR)
OR ( CAST(MONTH(REFERENCIA) AS VARCHAR)+'/'+CAST(YEAR(REFERENCIA) AS VARCHAR) =
(SELECT MAX(CAST(MONTH(REFERENCIA) AS VARCHAR)+'/'+CAST(YEAR(REFERENCIA) AS VARCHAR)) FROM TCSPRE PRE_MAX WHERE PRE_MAX.NUMCONTRATO = CON.NUMCONTRATO AND PRE_MAX.CODPROD = PRE.CODPROD)))


RETURN @VLRCONTRATO;

END




