


 DISABLE TRIGGER ALL ON TGFFRE;
--ALTER TABLE TGFFRE DISABLE ALL TRIGGERS;

DISABLE TRIGGER ALL ON TGFFIN;
--ALTER TABLE TGFFIN DISABLE ALL TRIGGERS;

DISABLE TRIGGER ALL ON TGFVAR;
--ALTER TABLE TGFVAR DISABLE ALL TRIGGERS;

DISABLE TRIGGER ALL ON TGFCAB;
--ALTER TABLE TGFCAB DISABLE ALL TRIGGERS;

DISABLE TRIGGER ALL ON TGFITE;
--ALTER TABLE TGFITE DISABLE ALL TRIGGERS;

DISABLE TRIGGER ALL ON TGFITS;
--ALTER TABLE TGFITS DISABLE ALL TRIGGERS;

DISABLE TRIGGER ALL ON TGFCUS;
--ALTER TABLE TGFCUS DISABLE ALL TRIGGERS;

DISABLE TRIGGER ALL ON TCIIBE;
--ALTER TABLE TCIIBE DISABLE ALL TRIGGERS;

DISABLE TRIGGER ALL ON TCIBEM;
--ALTER TABLE TCIBEM DISABLE ALL TRIGGERS;



--DELETA AS TUPLAS DA TABELA

--DELETE FROM TGFREN;
SELECT * FROM TGFREN;

--DELETE FROM TGFFRE;
SELECT * FROM TGFFRE;

--DELETE FROM TGFREF;
SELECT * FROM TGFREF;

--DELETE FROM TGFACF;
SELECT * FROM TGFACF;


--DELETE FROM TGFMDC;
SELECT * FROM TGFMDC;

--DELETE FROM TGFRCI;
SELECT * FROM TGFRCI;


--EXCLUIDO
DELETE FROM TGFFIN;
SELECT * FROM TGFFIN;
--

--EXCLUIDO
DELETE FROM TGFFIN_EXC;
SELECT * FROM TGFFIN_EXC;
--

--EXCLUIDO
DELETE FROM TGFMBC;
SELECT * FROM TGFMBC;
--

--DELETE FROM TGFVAR;
SELECT * FROM TGFVAR;

--DELETE FROM TGFLIV;
SELECT * FROM TGFLIV;

-- EXCLUIDO
DELETE FROM TGFCAB
WHERE TIPMOV<>'Z';
SELECT * FROM TGFCAB WHERE TIPMOV <> 'Z';
--


--DELETE FROM TGFITS;
SELECT * FROM TGFITS;

--DELETE FROM TCIMOV;
SELECT * FROM TCIMOV;

--DELETE FROM TCISAL;
SELECT * FROM TCISAL;

--EXCLUIDO
DELETE FROM TGFITE;
SELECT * FROM TGFITE;
--

--DELETE FROM TGFSER;
SELECT * FROM TGFSER;

--EXCLUIDO
DELETE FROM TGFCAB_EXC;
SELECT * FROM TGFCAB_EXC;
--

--EXCLUIDO
DELETE FROM TGFITE_EXC;
SELECT * FROM TGFITE_EXC;
--

--EXCLUIDO
DELETE FROM TGFLNF;
SELECT * FROM TGFLNF;
--

--DELETE FROM TGFCUS;
SELECT * FROM TGFCUS;

--EXCLUIDO
DELETE FROM TSIAVI;
SELECT * FROM TSIAVI;
--

--DELETE FROM TCITAX;
SELECT * FROM TCITAX;

/* TABELA IMOBILIZADOS */
--DELETE FROM TCIBEM;
/* BENS DA NOTA FISCAL */
--DELETE FROM TCIIBE;


--DELETE FROM TGFEST;
SELECT * FROM TGFEST;

--EXCLUIDO
DELETE FROM TSIRAV;
SELECT * FROM TSIRAV;
--

--DELETE FROM TCSSLT;
SELECT * FROM TCSSLT;

--DELETE FROM TCSITE;
SELECT * FROM TCSITE;

--DELETE FROM TCSFXO;
SELECT * FROM TCSFXO;

--DELETE FROM TCSOSE;
SELECT * FROM TCSOSE;

--DELETE FROM TGFITC;
SELECT * FROM TGFITC;

--DELETE FROM TGFCOT;
SELECT * FROM TGFCOT;

--DELETE FROM TGFPQE;
SELECT * FROM TGFPQE;

--DELETE FROM TGFQUE;
SELECT * FROM TGFQUE;

--DELETE FROM TGFTEL;
SELECT * FROM TGFTEL;

--EXCLUIDO
DELETE FROM TGFORD;
SELECT * FROM TGFORD;
--

--DELETE FROM TGFCAI;
SELECT * FROM TGFCAI;

--DELETE FROM TGFMCX;
SELECT * FROM TGFMCX;

--DELETE FROM TGFGIR;
SELECT * FROM TGFGIR;

--EXCLUIDO
DELETE FROM TGFORD;
SELECT * FROM TGFORD;
--

--EXCLUIDO
DELETE FROM TGFSBC;
SELECT * FROM TGFSBC;
--

--DELETE FROM TSILIB;
SELECT * FROM TSILIB;



--ATUALIZADO
-- ATUALIZA CADASTRO DA CONTA
UPDATE TSICTA SET SALDOBCO=NULL,SALDOREAL=NULL,DTIMPLANT=NULL;



-- ATUALIZA NUMERAÇÃO DA TGFNUM PARA 0.
UPDATE TGFNUM
SET ULTCOD = 0
WHERE ARQUIVO IN ('TGFGIR','TGFMCX','TGFCAI','TGFFRE','TGFFIN','TGFVAR','TGFCAB','TGFITE','TGFREN','TGFFRE','TGFREF','TGFFIN','TGFMBC','TGFCAB_EXC','TGFITE_EXC','TGFLNF','TGFCUS','TSIAVI','TCIBEM','TSIRAV','TCSOSE','TCSITE','TCSSLT','TCSFXO','TGFITC','TGFCOT','TGFPQE','TGFQUE','TGFCNF','TGFTEL');

-- HABILITA TRIGGERS

 ENABLE TRIGGER ALL ON TGFFRE;
--ALTER TABLE TGFFRE ENABLE ALL TRIGGERS;

 ENABLE TRIGGER ALL ON TGFFIN;
--ALTER TABLE TGFFIN ENABLE ALL TRIGGERS;

ENABLE TRIGGER ALL ON TGFVAR;
--ALTER TABLE TGFVAR ENABLE ALL TRIGGERS;

ENABLE TRIGGER ALL ON TGFCAB;
--ALTER TABLE TGFCAB ENABLE ALL TRIGGERS;

ENABLE TRIGGER ALL ON TGFITE;
--ALTER TABLE TGFITE ENABLE ALL TRIGGERS;

ENABLE TRIGGER ALL ON TGFITS;
--ALTER TABLE TGFITS ENABLE ALL TRIGGERS;

ENABLE TRIGGER ALL ON TGFCUS;
--ALTER TABLE TGFCUS ENABLE ALL TRIGGERS;

ENABLE TRIGGER ALL ON TCIIBE;
--ALTER TABLE TCIIBE ENABLE ALL TRIGGERS;

ENABLE TRIGGER ALL ON TCIBEM;
--ALTER TABLE TCIBEM ENABLE ALL TRIGGERS;

